//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CR.rc
//
#define IDR_SRVR_INPLACE                4
#define IDR_SRVR_EMBEDDED               5
#define IDR_CNTR_INPLACE                6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_CR_FORM                     101
#define IDP_FAILED_TO_CREATE            102
#define IDR_MAINFRAME                   128
#define IDR_CRTYPE                      129
#define IDB_BITMAP1                     130
#define IDB_BITMAP2                     131
#define IDD_DIALOG_POINTMATRIX          132
#define IDD_DIALOG_CTRL                 136
#define IDD_DIALOG_CTRL_INPUT           136
#define IDB_BITMAP_BACK                 138
#define IDB_BITMAP_MASK                 139
#define IDC_CURSOR_ERAZOR               141
#define IDC_CURSOR_PEN                  142
#define IDD_DIALOG_CTRL_BPNET           143
#define IDD_DIALOG_CTRL_OUTPUT          144
#define IDI_ICON_OUTPUT                 145
#define IDI_ICON_BPNET                  146
#define IDI_ICON_INPUT                  147
#define IDB_BITMAP_COLOR                151
#define IDB_BITMAP_TOOLBAR              152
#define IDB_BITMAP_TOOLBAR_COLD         154
#define IDC_EDIT1                       1005
#define IDC_EDIT_ERROR                  1005
#define IDC_EDIT_SAMPLE                 1005
#define IDC_EDIT_RELATIVE               1006
#define IDC_EDIT_STEP                   1007
#define IDC_BUTTON_COLOR                1008
#define IDC_EDIT_MAXERROR               1008
#define IDC_BUTTON_BAKCOLOR             1009
#define IDC_BUTTON_COLOR_PAT            1010
#define IDC_BUTTON_BAKCOLOR_PAT         1011
#define IDC_COMBO_POINTSIZE             1014
#define IDC_COMBO_OUTPUT                1015
#define IDC_COMBO_ROWS                  1015
#define IDC_SLIDER_WIDTH                1016
#define IDC_SLIDER_HEIGHT               1017
#define IDC_COMBO_COLS                  1018
#define IDC_BUTTON_RESET                1019
#define IDC_SLIDER                      1020
#define IDC_COMBO_HEIGHT                1020
#define IDC_SLIDER_WIDTH_PAT            1021
#define IDC_SLIDER_HEIGHT_PAT           1022
#define IDC_RADIO1                      1023
#define IDC_STATIC_RADIOGROUP           1024
#define IDC_RADIO5                      1024
#define IDC_BUTTON_RESET_PAT            1025
#define IDC_RADIO2                      1026
#define IDC_RADIO3                      1027
#define IDC_RADIO4                      1028
#define IDC_BUTTON_PREPRO               1029
#define IDC_COMBO_WIDTH                 1030
#define IDC_BUTTON_SHOW                 1031
#define IDC_BUTTON_HIDE                 1032
#define IDC_STATIC_MATRIX               1033
#define IDC_STATIC_CHART                1034
#define IDC_STATIC_TIME                 1037
#define IDC_LIST_RESULT                 1038
#define IDC_STATIC_RESULT               1039
#define IDC_COMBO_HIDE                  1039
#define IDC_BUTTON1                     1040
#define IDC_COMBO_SUBSRATE              1040
#define IDC_BUTTON_SAMPLE               1040
#define IDC_STATIC_AVERTIME             1041
#define IDC_COMBO_PLUSRATE              1041
#define IDC_STATIC_TEXT                 1042
#define IDC_STATIC_MAXERR               1042
#define IDC_BUTTON_TRAIN                1043
#define IDC_STATIC_MINERR               1043
#define IDC_CHECK_SAMPLE                1044
#define IDC_BUTTON_SAMPLE_SUB           1045
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_256ToGray                    32778
#define ID_GrayToWhiteBlack             32779
#define ID_prcSharp                     32780
#define ID_RemoveNoise                  32781
#define ID_AdjustSlope                  32782
#define ID_prcDivide                    32783
#define ID_Standarize                   32784
#define ID_ShrinkAlign                  32785
#define ID_SHOWRESULT                   32786
#define ID_PREPRO_ALL                   32787
#define ID_ADD_SAMPLE                   32788
#define ID_MATRIX_88                    32789
#define ID_MATRIX_816                   32790
#define ID_MATRIX_832                   32791
#define ID_MATRIX_1616                  32792
#define ID_MATRIX_168                   32793
#define ID_MATRIX_1632                  32794
#define ID_MATRIX_328                   32795
#define ID_MATRIX_3216                  32796
#define ID_MATRIX_3232                  32797
#define ID_HANDPAT_88                   32798
#define ID_HANDPAT_816                  32799
#define ID_HANDPAT_832                  32800
#define ID_HANDPAT_168                  32801
#define ID_HANDPAT_1616                 32802
#define ID_HANDPAT_1632                 32803
#define ID_HANDPAT_328                  32804
#define ID_HANDPAT_3216                 32805
#define ID_HANDPAT_3232                 32806
#define ID_PICTURE_OPEN                 32807
#define ID_CTRL_INPUT                   32808
#define ID_CTRL_BPNET                   32809
#define ID_CTRL_OUTPUT                  32810
#define ID_SAMPLE_SAVE                  32811
#define ID_INPUT_MATRIX                 37123
#define ID_INPUT_HANDPAT                37124
#define ID_INPUT_PICTURE                37125
#define ID_INPUT_CTRLPAT                37126
#define ID_INPUT_FLOATPAT               37127
#define ID_TRAIN                        37128
#define ID_RECGNIZE                     37129

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32812
#define _APS_NEXT_CONTROL_VALUE         1048
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
